// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // ✅ Добавлено
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// ✅ Добавляем Web конфигурацию
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyD8QODxCpC4v0T0EKlUXlDcrUMQnRHXUmM",
    authDomain: "qamqor-72e53.firebaseapp.com",
    projectId: "qamqor-72e53",
    storageBucket: "qamqor-72e53.firebasestorage.app",
    messagingSenderId: "1062961311521",
    appId: "1:1062961311521:web:8ee241fb302978cea39860",
    measurementId: "G-HZV2V7X0T8",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHmsZYU3n14dJnHBJIh9qabfYq3psMjr8',
    appId: '1:1062flutter pub get961311521:android:090c30abc2fe9230a39860',
    messagingSenderId: '1062961311521',
    projectId: 'qamqor-72e53',
    storageBucket: 'qamqor-72e53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyybb7Wub8q95jE1HucQi9QjDODI6b2y4',
    appId: '1:1062961311521:ios:e894f5bfc1ecba93a39860',
    messagingSenderId: '1062961311521',
    projectId: 'qamqor-72e53',
    storageBucket: 'qamqor-72e53.firebasestorage.app',
    iosBundleId: 'com.example.womenHealth',
  );
}
